
services:
  web:
    image: php:8.2-apache
    container_name: cafeteria_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
    command: >
      bash -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql pgsql && apache2-foreground"

  db:
    image: postgres:15
    container_name: cafeteria_db
    environment:
      POSTGRES_DB: cafeteria_db
      POSTGRES_USER: usuario_cafe
      POSTGRES_PASSWORD: clave_secreta
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
